# Generated by Django 4.1.13 on 2024-05-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_task_task_check_completion_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
