# Generated by Django 4.1.13 on 2024-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
